language: python
python:
  - "3.6"      # current default Python on Travis CI
# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
# command to run tests
script:
  - python test_api.py 
  - coala -C         # Run coala in non-interactive mode.
